name: Build and Push Sentry Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. 拉取 Sentry 自部署仓库代码
    - name: Clone Sentry self-hosted repo
      run: |
        git clone https://github.com/getsentry/self-hosted.git
        cd self-hosted

    # 3. 运行 install.sh 脚本
    - name: Run install.sh script
      run: |
        cd self-hosted
        chmod +x install.sh
        ./install.sh --no-report-self-hosted-issues

    # 4. 登录 GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # 5. 推送 Docker 镜像到 GitHub Container Registry
    - name: Push Docker images
      run: |
        docker tag sentry-onpremise-local ghcr.io/${{ github.repository_owner }}/sentry:latest
        docker push ghcr.io/${{ github.repository_owner }}/sentry:latest
